apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: {{ .Values.service.name | default "web" | quote}}
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.service.type | default "ClusterIP" | quote}}
