http.host = 0.0.0.0
http.port = 80
http.enabled = true
https.enabled = false

source.static = FilesystemSource
FilesystemSource.lookup_strategy = BasicLookupStrategy
FilesystemSource.BasicLookupStrategy.path_prefix = /var/www/iipsrv/tests/

endpoint.iiif.1.enabled = false
endpoint.iiif.2.enabled = true
