FROM debian:13

RUN --mount=type=cache,target=/var/cache/apt \
    export DEBIAN_FRONTEND=noninteractive && \
    apt update && apt dist-upgrade -y --no-install-recommends && \
    apt install -y --no-install-recommends \
        apache2 \
        libapache2-mod-fcgid \
        iipimage-server \
        locales-all && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /var/www/iipsrv/tests && \
    cp -p /usr/lib/iipimage-server/iipsrv.fcgi /var/www/iipsrv/ && \
    chown -R www-data:www-data /var/www/iipsrv

RUN rm -f /etc/apache2/mods-available/iipsrv.conf
COPY /install/iipsrv.conf /etc/apache2/mods-available/iipsrv.conf

RUN sed -i 's~^Listen.*~Listen 8080~' /etc/apache2/ports.conf && \
    sed -i 's~^<VirtualHost \*:80>~<VirtualHost *:8080>~' /etc/apache2/sites-available/000-default.conf && \
    a2enmod fcgid && \
    a2enmod iipsrv

EXPOSE 8080
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]