test_ids = {
    'frodo_id': 113,
    'sam_id': 118,
    'ring_id': 116,
    'travel_id': 119,
    'home_id': 108,
    'kitchen_id': 110,
    'location_kitchen_id': 111,
    'location_home_id': 109,
    'shire_id': 104,
    'location_shire_id': 105,
    'mordor_id': 120,
    'location_mordor_id': 121,

    'place_id': 65,
    'height_id': 102,
    'weight_id': 103,
    'suza_id': 106,
    'geonames_id': 1,
    'lotr_id': 107,
    'picture_id': 112,
    'file_without_id': 115,
    'silmarillion_id': 122,

    'administrative_id': 83,
    'austria_id': 84,
    'wien_id': 85,
    'nieder_id': 86,
    'germany_id': 87,
    'italy_id': 88,
    'czech_id': 89,
    'slovakia_id': 90,
    'slovenia_id': 91,
    'marcha_id': 94,
    'comitatus_id': 95,
    'carantinia_id': 93,
    'serbia_id': 96,
    'historical_place_id': 92,



    'actor_function_id': 16,
    'actor_r_id': 53,
    'economical_id': 63,
    'provider_id': 64,
    'kindredship_id': 54,
    'parent_id': 55,
    'political_id': 60,
    'ally_id': 61,
    'leader_id': 62,
    'social_id': 56,
    'enemy_id': 58,
    'friend_id': 57,
    'mentor_id': 59,
    'victim_id': 29,
    'involvement_id': 26,
    'sponsor_id': 28,
    'offender_id': 30,



    'abbot_id': 18,
    'bishop_id': 17,
    'emperor_id': 20,
    'count_id': 21,
    'creator_id': 27,
    'deposit_id': 79,
    'pope_id': 19,
    'king_id': 22,

    'article_id': 5,
    'artifact_id': 23,
    'bibliography_id': 3,
    'book_id': 6,
    'charter_id': 43,
    'source_id': 42,
    'charter_edition_id': 8,
    'edition_id': 7,
    'letter_edition_id': 9,
    'chronicle_edition_id': 10,
    'event_id': 34,
    'stratigraphic_id': 77,
    'feature_id': 74,
    'inbook_id': 4,
    'source_translation_id': 97,
    'transliteration_id': 100,
    'original_text_id': 98,
    'translation_id': 99,


    'battle_id': 40,
    'boundary_id': 72,
    'burial_id': 78,
    'burial_site_id': 69,
    'economic_site_id': 71,
    'ritual_site_id': 68,
    'cc_by_sa_id': 52,
    'cc_by_id': 51,
    'license_id': 47,
    'public_domain_id': 50,
    'open_license_id': 49,
    'proprietary_id': 48,
    'change_id': 35,
    'coin_id': 24,
    'conflict_id': 39,
    'sale_id': 37,
    'contract_id': 46,
    'dimensions_id': 101,
    'donation_id': 36,
    'exchange_id': 38,
    'female_id': 32,
    'male_id': 33,
    'sex_id': 31,
    'grave_id': 75,
    'human_remains_id': 80,
    'infrastructure_id': 70,
    'link_id': 12,
    'letter_id': 45,
    'lower_body_id': 82,
    'military_facility_id': 67,
    'statue_id': 25,
    'pit_id': 76,
    'raid_id': 41,
    'settlement_id': 66,
    'testament_id': 44,
    'topographical_id': 73,
    'upper_body_id': 81,






    'close_match_id': 15,
    'exact_match_id': 14,
    'external_match_id': 13,
    'external_reference_id': 11,



}
