test_node_entities = {'nodes': [
    {'id': 84,
     'label': 'Austria',
     'url': 'http://local.host/api/0.2/entity/84'},
    {'id': 89,
     'label': 'Czech Republic',
     'url': 'http://local.host/api/0.2/entity/89'},
    {'id': 87,
     'label': 'Germany',
     'url': 'http://local.host/api/0.2/entity/87'},
    {'id': 88,
     'label': 'Italy',
     'url': 'http://local.host/api/0.2/entity/88'},
    {'id': 90,
     'label': 'Slovakia',
     'url': 'http://local.host/api/0.2/entity/90'},
    {'id': 91,
     'label': 'Slovenia',
     'url': 'http://local.host/api/0.2/entity/91'}]}
test_node_entities_all = {'nodes': [
    {'id': 84,
     'label': 'Austria',
     'url': 'http://local.host/api/0.2/entity/84'},
    {'id': 89,
     'label': 'Czech Republic',
     'url': 'http://local.host/api/0.2/entity/89'},
    {'id': 87,
     'label': 'Germany',
     'url': 'http://local.host/api/0.2/entity/87'},
    {'id': 88,
     'label': 'Italy',
     'url': 'http://local.host/api/0.2/entity/88'},
    {'id': 90,
     'label': 'Slovakia',
     'url': 'http://local.host/api/0.2/entity/90'},
    {'id': 91,
     'label': 'Slovenia',
     'url': 'http://local.host/api/0.2/entity/91'},
    {'id': 86,
     'label': 'Niederösterreich',
     'url': 'http://local.host/api/0.2/entity/86'},
    {'id': 85,
     'label': 'Wien',
     'url': 'http://local.host/api/0.2/entity/85'}]}
